version: 2.1
jobs:
  build-siril-master:
    macos:
        xcode: "13.1.0"

    steps:
        - checkout
        - run:
            name: Cleanup /usr/local
            command: sudo rm -rf /usr/local/*
        - run:
            name: Setup Python3
            command: |
              cd ~/
              curl -L 'https://www.python.org/ftp/python/3.9.7/python-3.9.7-macos11.pkg' > python-3.9.7-macosx11.pkg
              sudo installer -pkg python-3.9.7-macosx11.pkg -target /
              # Certificates are outdated, most likely after the recent
              # Let's Encrypt root certs fiasco. This fixes it by
              # updating the certs.
              open /Applications/Python\ 3.9/Install\ Certificates.command
        - run:
            name: Setup 10.12 SDK
            command: |
              cd /Library/Developer/CommandLineTools/SDKs
              sudo curl -L 'https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.12.sdk.tar.xz' | sudo tar -xzf -
              echo 'export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk' > ~/.profile
              echo 'export MACOSX_DEPLOYMENT_TARGET=10.12' >> ~/.profile
        - restore_cache:
            keys:
              - jhbuild-v20
        - run:
            name: Setup JHBuild
            command: |
              cd $HOME
              mkdir -p ~/.config && cp ~/project/jhbuildrc-gtk-osx-gimp-2.99 ~/.config/jhbuildrc-custom
              curl https://gitlab.gnome.org/samm-git/gtk-osx/raw/gimp/gtk-osx-setup.sh > gtk-osx-setup.sh
              chmod +x gtk-osx-setup.sh
              echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH:$HOME/.new_local/bin"' >> ~/.profile
              echo 'export ARCHFLAGS="-arch x86_64"' >> ~/.profile
              # PYTHON variable seems to be incorrectly set
              echo 'export PYTHON=/Library/Frameworks/Python.framework/Versions/3.9/bin/python3' >> ~/.profile
              # Unclear why this is needed, but if missing, jhbuild fails in some circumstances
              echo 'export PYENV_VERSION="3.9.7"' >> ~/.profile
              source ~/.profile
              PIPENV_YES=1 ./gtk-osx-setup.sh
              $HOME/.new_local/bin/jhbuild bootstrap-gtk-osx-gimp
              cat ~/.profile
        - save_cache:
            paths:
              - ~/.new_local
              - ~/gtk
              - ~/.config
            key: jhbuild-v20
        - run:
            name: Setup gtk-mac-bundler
            command: |
              cd ~/Source
              git clone https://gitlab.gnome.org/lukaso/gtk-mac-bundler
              cd gtk-mac-bundler
              make install
        # we can try to make it automatically depended on the corresponding modules
        - restore_cache:
            keys:
              - siril-0.99.11-v5
              - siril-deps-v17
              - bootstrap-v11
        - run:
            name: Bootstrap
            command: source ~/.profile && jhbuild build icu libnsgif meta-gtk-osx-freetype meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: bootstrap-v11
        - run:
            name: Build Siril dependencies
            command: |
              source ~/.profile && jhbuild build $(jhbuild info siril|grep '^Requires:'|sed -e 's|^Requires:||' -e 's|gegl||'|tr -d ',')
        - run:
            name: Cleanup
            command: find  ~/gtk/source -type d -mindepth 1 -maxdepth 1 | xargs -I% rm -rf %/*
        - save_cache:
            paths:
              - ~/gtk
            key: siril-deps-v17
        - run:
            name: Build SIRIL
            command: |
              source ~/.profile
              jhbuild build siril
        - save_cache:
            paths:
              - ~/gtk
            key: siril-0.99.11-v5
#        - run:
#            name: Importing signing certificate
#            command: |
#              mkdir ${HOME}/codesign && cd ${HOME}/codesign
#              echo "$osx_crt" | base64 -D > gnome.pfx
#              curl 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer' > apple.cer
##              security create-keychain -p "" signchain
#              security set-keychain-settings signchain
#              security unlock-keychain -u signchain
#              security list-keychains  -s "${HOME}/Library/Keychains/signchain-db" "${HOME}/Library/Keychains/login.keychain-db"
#              security import apple.cer -k signchain  -T /usr/bin/codesign
#              security import gnome.pfx  -k signchain -P "$osx_crt_pw" -T /usr/bin/codesign
#              security set-key-partition-list -S apple-tool:,apple: -k "" signchain
#              rm -rf ${HOME}/codesign
        - run:
            name: Creating DMG package
            command: |
              source ~/.profile
              cd ${HOME}/project/package
              jhbuild run ./build.sh
#        - run:
#            name:  Notarizing DMG package
#            command: |
#              xcrun altool --notarize-app --file /tmp/artifacts/gimp-*.dmg -u "${notarization_login}" --primary-bundle-id -p "${notarization_password}"
        - store_artifacts:
            path: /tmp/artifacts
            destination: builds

workflows:
  version: 2.1
  build-different-versions:
    jobs:
      - build-siril-master
